# Generated by Django 4.2.2 on 2024-09-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_payment_method_alter_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                blank=True,
                help_text="Укажите статус платежа",
                max_length=50,
                null=True,
                verbose_name="Статус платежа",
            ),
        ),
    ]
