# Generated by Django 5.1.1 on 2024-09-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True, help_text="Опишите урок", null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(
                help_text="Укажите урок", max_length=100, verbose_name="Урок"
            ),
        ),
    ]
