# Generated by Django 4.2.2 on 2024-09-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Укажите дату и время обновления",
                verbose_name="Обновлено",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Укажите дату и время обновления",
                verbose_name="Обновлено",
            ),
        ),
    ]
